### ISSUE TITLE
Duplicating of WooThemes Sensei lessons

### ISSUE THREAD

**Issue by aheckler** [johnjamesjacoby/post-type-switcher#4]
When editing an existing Lesson in Sensei, Post Type Switcher duplicates the lesson. 

To repro:

1. Install Sensei and create a lesson with some dummy content.
2. Install and activate Post Type Switcher.
3. Edit the lesson content. Don't touch the post type switcher control.
4. Click the Update button.
5. Lesson saves correctly but is duplicated in the All Lessons screen.
6. Deactivate Post Type Switcher.
7. Repeat steps 3-4 above. No duplicated lesson this time.

What's odd is that this doesn't occur with other Sensei post types, e.g. Courses.

**Comment by richardmtl** [comment]
I was able to reproduce this on another site, same issue, same resolution.

**Comment by johnjamesjacoby** [comment]
This is fixed in 2.0.0.

Previous versions hooked to `save_post` and called `set_post_type()`, which resulted in calling `clean_post_cache()` a second time, causing a race condition.

2.0.0 and beyond filter `wp_insert_post_data` and `wp_insert_attachment_data` and override the `post_type` before the post is updated the first time.

Thanks for the report!
